package com.cordys.coe.util.i18n;

import com.cordys.coe.util.i18n.CoEMessage;
import com.cordys.coe.util.i18n.CoEMessageSet;

/**
 * This code is generated by running com.cordys.coe.util.i18n.CoEMessageClassGenerator.
 */
public class TestMessages
{
	/**
	 * Holds the definition of the CoE message set.
	 */
	public static final CoEMessageSet MESSAGE_SET = new CoEMessageSet("com.cordys.coe.util.i18n", "TestMessages");

	/**
	 * Holds the definition of the message with ID some.nice.identifier.
	 * Message text:
	 * some.nice.identifier from default.
	 */
	public static final CoEMessage SOME_NICE_IDENTIFIER = new CoEMessage(MESSAGE_SET, "some.nice.identifier");
	/**
	 * Holds the definition of the message with ID only.in.default.
	 * Message text:
	 * only defined in the default file with parameter {0}.
	 */
	public static final CoEMessage ONLY_IN_DEFAULT = new CoEMessage(MESSAGE_SET, "only.in.default");
	/**
	 * Holds the definition of the message with ID different.string.
	 * Message text:
	 * different.string from default.
	 */
	public static final CoEMessage DIFFERENT_STRING = new CoEMessage(MESSAGE_SET, "different.string");

}