/**
 * (c) 2006 Cordys R&D B.V. All rights reserved. The computer program(s) is the
 * proprietary information of Cordys B.V. and provided under the relevant
 * License Agreement containing restrictions on use and disclosure. Use is
 * subject to the License Agreement.
 */
package com.cordys.coe.util.template;

/**
 * Contains message names that can be used in the event processing pipeline variables. This doesn't
 * define all message names, but just given a handy place to keep the most common names. To get the
 * name to be used in a variable, use the <code>getVarName()</code> method.
 *
 * @author  mpoyhone
 */
public enum EVariableNames
{
    /**
     * This is the current message in the execution context.
     */
    MSG,
    /**
     * Initial message generated by the listener.
     */
    INIT_MSG,
    /**
     * Method implementation XML. Set by the bus SOAP listener.
     */
    SOAP_METHOD_IMPL,
    /**
     * User DN of the calling user. Set by the bus SOAP listener.
     */
    SOAP_USERDN,
    /**
     * The flow instance ID received in the SOAP response. Set by start flow action.
     */
    FLOW_INSTANCE_ID,
    /**
     * Flow output message XML. Set by start flow action.
     */
    FLOW_OUTPUT,
    /**
     * Message ID of the sent message.
     */
    JMS_MESSAGE_ID;

    /**
     * Return the variable name in the execution context.
     *
     * @return  Variable name.
     */
    public String getVarName()
    {
        return toString();
    }
}
