/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../libs/java1_4_2/jni.h"
/* Header for class com_cordys_coe_util_system_processes_SystemProcess */

#ifndef _Included_com_cordys_coe_util_system_processes_SystemProcess
#define _Included_com_cordys_coe_util_system_processes_SystemProcess
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
