/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../libs/java1_4_2/jni.h"
/* Header for class com_cordys_coe_util_system_processes_SystemProcessList */

#ifndef _Included_com_cordys_coe_util_system_processes_SystemProcessList
#define _Included_com_cordys_coe_util_system_processes_SystemProcessList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cordys_coe_util_system_processes_SystemProcessList
 * Method:    nativeGetSystemProcesses
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_cordys_coe_util_system_processes_SystemProcessList_nativeGetSystemProcesses
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cordys_coe_util_system_processes_SystemProcessList
 * Method:    nativeKillProcess
 * Signature: (Lcom/cordys/coe/util/system/processes/SystemProcess;)V
 */
JNIEXPORT void JNICALL Java_com_cordys_coe_util_system_processes_SystemProcessList_nativeKillProcess
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cordys_coe_util_system_processes_SystemProcessList
 * Method:    nativeEnableKill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cordys_coe_util_system_processes_SystemProcessList_nativeEnableKill
  (JNIEnv *, jobject);

/*
 * Class:     com_cordys_coe_util_system_processes_SystemProcessList
 * Method:    nativeDisableKill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cordys_coe_util_system_processes_SystemProcessList_nativeDisableKill
  (JNIEnv *, jobject);

/*
 * Class:     com_cordys_coe_util_system_processes_SystemProcessList
 * Method:    getCurrentProcessID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_cordys_coe_util_system_processes_SystemProcessList_getCurrentProcessID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
